services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - ~/docker/homeschool/db:/var/lib/postgresql/data/
    environment:
      #POSTGRES_DB: yourdbname
      #POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
 #   volumes:
 #     - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DEBUG: 'true'
